name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 使用您项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Preview the build
        run: npm run preview
